// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SMMPMessages.proto

package SMMPClient.SMMP;

public interface SMMPAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SMMPAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageID = 1;</code>
   * @return The messageID.
   */
  String getMessageID();
  /**
   * <code>string messageID = 1;</code>
   * @return The bytes for messageID.
   */
  com.google.protobuf.ByteString
      getMessageIDBytes();

  /**
   * <code>bytes signature = 2;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <code>bytes certificate = 3;</code>
   * @return The certificate.
   */
  com.google.protobuf.ByteString getCertificate();
}
