// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SMMPMessages.proto

package SMMPClient.SMMP;

public final class SMMPMessages {
  private SMMPMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SMMPMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SMMPMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SMMPAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SMMPAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022SMMPMessages.proto\"p\n\013SMMPMessage\022\023\n\013i" +
      "sEncrypted\030\001 \001(\010\022\023\n\013requiresAck\030\002 \001(\010\022\021\n" +
      "\tsignature\030\003 \001(\014\022\023\n\013certificate\030\004 \001(\014\022\017\n" +
      "\007payload\030\005 \001(\014\"D\n\007SMMPAck\022\021\n\tmessageID\030\001" +
      " \001(\t\022\021\n\tsignature\030\002 \001(\014\022\023\n\013certificate\030\003" +
      " \001(\014B\032\n\010MMS.SMMPB\014SMMPMessagesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SMMPMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SMMPMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SMMPMessage_descriptor,
        new String[] { "IsEncrypted", "RequiresAck", "Signature", "Certificate", "Payload", });
    internal_static_SMMPAck_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SMMPAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SMMPAck_descriptor,
        new String[] { "MessageID", "Signature", "Certificate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
