// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SMMPMessages.proto

package SMMPClient.MessageFormats;

public interface ProtocolMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SMMPClient.SMMP.ProtocolMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SMMPClient.SMMP.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.SMMPClient.SMMP.MessageType type = 1;</code>
   * @return The type.
   */
  SMMPClient.MessageFormats.MessageType getType();

  /**
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
