// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SMMPMessages.proto

package SMMPClient.MessageFormats;

public final class SMMPMessages {
  private SMMPMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SMMPClient_SMMP_ProtocolMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SMMPClient_SMMP_ProtocolMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SMMPClient_SMMP_SMMPMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SMMPClient_SMMP_SMMPMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SMMPClient_SMMP_SMMPAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SMMPClient_SMMP_SMMPAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SMMPMessages.proto\022\017SMMPClient.SMMP\"N\n" +
      "\017ProtocolMessage\022*\n\004type\030\001 \001(\0162\034.SMMPCli" +
      "ent.SMMP.MessageType\022\017\n\007content\030\002 \001(\014\"\203\001" +
      "\n\013SMMPMessage\022\021\n\tmessageID\030\001 \001(\t\022\023\n\013isEn" +
      "crypted\030\002 \001(\010\022\023\n\013requiresAck\030\003 \001(\010\022\021\n\tsi" +
      "gnature\030\004 \001(\014\022\023\n\013certificate\030\005 \001(\014\022\017\n\007pa" +
      "yload\030\006 \001(\014\"D\n\007SMMPAck\022\021\n\tmessageID\030\001 \001(" +
      "\t\022\021\n\tsignature\030\002 \001(\014\022\023\n\013certificate\030\003 \001(" +
      "\014*#\n\013MessageType\022\013\n\007MESSAGE\020\000\022\007\n\003ACK\020\001B\020" +
      "B\014SMMPMessagesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SMMPClient_SMMP_ProtocolMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SMMPClient_SMMP_ProtocolMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SMMPClient_SMMP_ProtocolMessage_descriptor,
        new java.lang.String[] { "Type", "Content", });
    internal_static_SMMPClient_SMMP_SMMPMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SMMPClient_SMMP_SMMPMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SMMPClient_SMMP_SMMPMessage_descriptor,
        new java.lang.String[] { "MessageID", "IsEncrypted", "RequiresAck", "Signature", "Certificate", "Payload", });
    internal_static_SMMPClient_SMMP_SMMPAck_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SMMPClient_SMMP_SMMPAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SMMPClient_SMMP_SMMPAck_descriptor,
        new java.lang.String[] { "MessageID", "Signature", "Certificate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
