// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MMTPMessages.proto

package Protocols.MMTP.MessageFormats;

public interface DirectApplicationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DirectApplicationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>repeated string recipients = 2;</code>
   * @return A list containing the recipients.
   */
  java.util.List<String>
      getRecipientsList();
  /**
   * <code>repeated string recipients = 2;</code>
   * @return The count of recipients.
   */
  int getRecipientsCount();
  /**
   * <code>repeated string recipients = 2;</code>
   * @param index The index of the element to return.
   * @return The recipients at the given index.
   */
  String getRecipients(int index);
  /**
   * <code>repeated string recipients = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the recipients at the given index.
   */
  com.google.protobuf.ByteString
      getRecipientsBytes(int index);

  /**
   * <code>string sender = 3;</code>
   * @return The sender.
   */
  String getSender();
  /**
   * <code>string sender = 3;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return Whether the expires field is set.
   */
  boolean hasExpires();
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return The expires.
   */
  com.google.protobuf.Timestamp getExpires();
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresOrBuilder();

  /**
   * <code>bytes payload = 5;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
