// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MMTPMessages.proto

package Protocols.MMTP.MessageFormats;

/**
 * Protobuf enum {@code MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>REGISTER = 0;</code>
   */
  REGISTER(0),
  /**
   * <code>UNREGISTER = 1;</code>
   */
  UNREGISTER(1),
  /**
   * <code>DIRECT_APPLICATION_MESSAGE = 2;</code>
   */
  DIRECT_APPLICATION_MESSAGE(2),
  /**
   * <code>SUBJECT_CAST_APPLICATION_MESSAGE = 3;</code>
   */
  SUBJECT_CAST_APPLICATION_MESSAGE(3),
  /**
   * <code>ROUTING_UPDATE = 4;</code>
   */
  ROUTING_UPDATE(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>REGISTER = 0;</code>
   */
  public static final int REGISTER_VALUE = 0;
  /**
   * <code>UNREGISTER = 1;</code>
   */
  public static final int UNREGISTER_VALUE = 1;
  /**
   * <code>DIRECT_APPLICATION_MESSAGE = 2;</code>
   */
  public static final int DIRECT_APPLICATION_MESSAGE_VALUE = 2;
  /**
   * <code>SUBJECT_CAST_APPLICATION_MESSAGE = 3;</code>
   */
  public static final int SUBJECT_CAST_APPLICATION_MESSAGE_VALUE = 3;
  /**
   * <code>ROUTING_UPDATE = 4;</code>
   */
  public static final int ROUTING_UPDATE_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return REGISTER;
      case 1: return UNREGISTER;
      case 2: return DIRECT_APPLICATION_MESSAGE;
      case 3: return SUBJECT_CAST_APPLICATION_MESSAGE;
      case 4: return ROUTING_UPDATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return MMTPMessages.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MessageType)
}

