// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MMTPMessages.proto

package Protocols.MMTP.MessageFormats;

/**
 * Protobuf type {@code Register}
 */
public final class Register extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Register)
    RegisterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Register.newBuilder() to construct.
  private Register(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Register() {
    interests_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Register();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MMTPMessages.internal_static_Register_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MMTPMessages.internal_static_Register_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Register.class, Builder.class);
  }

  private int bitField0_;
  public static final int INTERESTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList interests_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * List of strings representing interests
   * </pre>
   *
   * <code>repeated string interests = 1;</code>
   * @return A list containing the interests.
   */
  public com.google.protobuf.ProtocolStringList
      getInterestsList() {
    return interests_;
  }
  /**
   * <pre>
   * List of strings representing interests
   * </pre>
   *
   * <code>repeated string interests = 1;</code>
   * @return The count of interests.
   */
  public int getInterestsCount() {
    return interests_.size();
  }
  /**
   * <pre>
   * List of strings representing interests
   * </pre>
   *
   * <code>repeated string interests = 1;</code>
   * @param index The index of the element to return.
   * @return The interests at the given index.
   */
  public String getInterests(int index) {
    return interests_.get(index);
  }
  /**
   * <pre>
   * List of strings representing interests
   * </pre>
   *
   * <code>repeated string interests = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the interests at the given index.
   */
  public com.google.protobuf.ByteString
      getInterestsBytes(int index) {
    return interests_.getByteString(index);
  }

  public static final int WANT_DIRECT_MESSAGES_FIELD_NUMBER = 2;
  private boolean wantDirectMessages_ = false;
  /**
   * <pre>
   * Boolean indicating if the agent wishes to receive direct messages
   * </pre>
   *
   * <code>optional bool want_direct_messages = 2;</code>
   * @return Whether the wantDirectMessages field is set.
   */
  @Override
  public boolean hasWantDirectMessages() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Boolean indicating if the agent wishes to receive direct messages
   * </pre>
   *
   * <code>optional bool want_direct_messages = 2;</code>
   * @return The wantDirectMessages.
   */
  @Override
  public boolean getWantDirectMessages() {
    return wantDirectMessages_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < interests_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, interests_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(2, wantDirectMessages_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < interests_.size(); i++) {
        dataSize += computeStringSizeNoTag(interests_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInterestsList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, wantDirectMessages_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Register)) {
      return super.equals(obj);
    }
    Register other = (Register) obj;

    if (!getInterestsList()
        .equals(other.getInterestsList())) return false;
    if (hasWantDirectMessages() != other.hasWantDirectMessages()) return false;
    if (hasWantDirectMessages()) {
      if (getWantDirectMessages()
          != other.getWantDirectMessages()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInterestsCount() > 0) {
      hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
      hash = (53 * hash) + getInterestsList().hashCode();
    }
    if (hasWantDirectMessages()) {
      hash = (37 * hash) + WANT_DIRECT_MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getWantDirectMessages());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Register parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Register parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Register parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Register parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Register parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Register parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Register parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Register parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Register parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Register parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Register parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Register parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Register prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Register}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Register)
          RegisterOrBuilder
  {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MMTPMessages.internal_static_Register_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MMTPMessages.internal_static_Register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Register.class, Builder.class);
    }

    // Construct using MMS.MMTP.Register.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      interests_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      wantDirectMessages_ = false;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MMTPMessages.internal_static_Register_descriptor;
    }

    @Override
    public Register getDefaultInstanceForType() {
      return Register.getDefaultInstance();
    }

    @Override
    public Register build() {
      Register result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Register buildPartial() {
      Register result = new Register(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Register result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        interests_.makeImmutable();
        result.interests_ = interests_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.wantDirectMessages_ = wantDirectMessages_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Register) {
        return mergeFrom((Register)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Register other) {
      if (other == Register.getDefaultInstance()) return this;
      if (!other.interests_.isEmpty()) {
        if (interests_.isEmpty()) {
          interests_ = other.interests_;
          bitField0_ |= 0x00000001;
        } else {
          ensureInterestsIsMutable();
          interests_.addAll(other.interests_);
        }
        onChanged();
      }
      if (other.hasWantDirectMessages()) {
        setWantDirectMessages(other.getWantDirectMessages());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              ensureInterestsIsMutable();
              interests_.add(s);
              break;
            } // case 10
            case 16: {
              wantDirectMessages_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList interests_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureInterestsIsMutable() {
      if (!interests_.isModifiable()) {
        interests_ = new com.google.protobuf.LazyStringArrayList(interests_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @return A list containing the interests.
     */
    public com.google.protobuf.ProtocolStringList
        getInterestsList() {
      interests_.makeImmutable();
      return interests_;
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @return The count of interests.
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    public String getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    public com.google.protobuf.ByteString
        getInterestsBytes(int index) {
      return interests_.getByteString(index);
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @param index The index to set the value at.
     * @param value The interests to set.
     * @return This builder for chaining.
     */
    public Builder setInterests(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInterestsIsMutable();
      interests_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @param value The interests to add.
     * @return This builder for chaining.
     */
    public Builder addInterests(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInterestsIsMutable();
      interests_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @param values The interests to add.
     * @return This builder for chaining.
     */
    public Builder addAllInterests(
        Iterable<String> values) {
      ensureInterestsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, interests_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterests() {
      interests_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of strings representing interests
     * </pre>
     *
     * <code>repeated string interests = 1;</code>
     * @param value The bytes of the interests to add.
     * @return This builder for chaining.
     */
    public Builder addInterestsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureInterestsIsMutable();
      interests_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean wantDirectMessages_ ;
    /**
     * <pre>
     * Boolean indicating if the agent wishes to receive direct messages
     * </pre>
     *
     * <code>optional bool want_direct_messages = 2;</code>
     * @return Whether the wantDirectMessages field is set.
     */
    @Override
    public boolean hasWantDirectMessages() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Boolean indicating if the agent wishes to receive direct messages
     * </pre>
     *
     * <code>optional bool want_direct_messages = 2;</code>
     * @return The wantDirectMessages.
     */
    @Override
    public boolean getWantDirectMessages() {
      return wantDirectMessages_;
    }
    /**
     * <pre>
     * Boolean indicating if the agent wishes to receive direct messages
     * </pre>
     *
     * <code>optional bool want_direct_messages = 2;</code>
     * @param value The wantDirectMessages to set.
     * @return This builder for chaining.
     */
    public Builder setWantDirectMessages(boolean value) {

      wantDirectMessages_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Boolean indicating if the agent wishes to receive direct messages
     * </pre>
     *
     * <code>optional bool want_direct_messages = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWantDirectMessages() {
      bitField0_ = (bitField0_ & ~0x00000002);
      wantDirectMessages_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Register)
  }

  // @@protoc_insertion_point(class_scope:Register)
  private static final Register DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Register();
  }

  public static Register getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Register>
      PARSER = new com.google.protobuf.AbstractParser<Register>() {
    @Override
    public Register parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Register> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Register> getParserForType() {
    return PARSER;
  }

  @Override
  public Register getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

