// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MMTPMessages.proto

package Protocols.MMTP.MessageFormats;

public interface RoutingUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoutingUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string MRNs = 1;</code>
   * @return A list containing the mRNs.
   */
  java.util.List<String>
      getMRNsList();
  /**
   * <code>repeated string MRNs = 1;</code>
   * @return The count of mRNs.
   */
  int getMRNsCount();
  /**
   * <code>repeated string MRNs = 1;</code>
   * @param index The index of the element to return.
   * @return The mRNs at the given index.
   */
  String getMRNs(int index);
  /**
   * <code>repeated string MRNs = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the mRNs at the given index.
   */
  com.google.protobuf.ByteString
      getMRNsBytes(int index);

  /**
   * <code>repeated string subjects = 2;</code>
   * @return A list containing the subjects.
   */
  java.util.List<String>
      getSubjectsList();
  /**
   * <code>repeated string subjects = 2;</code>
   * @return The count of subjects.
   */
  int getSubjectsCount();
  /**
   * <code>repeated string subjects = 2;</code>
   * @param index The index of the element to return.
   * @return The subjects at the given index.
   */
  String getSubjects(int index);
  /**
   * <code>repeated string subjects = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the subjects at the given index.
   */
  com.google.protobuf.ByteString
      getSubjectsBytes(int index);
}
