// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MMTPMessages.proto

package Protocols.MMTP.MessageFormats;

/**
 * Protobuf type {@code RoutingUpdate}
 */
public final class RoutingUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RoutingUpdate)
    RoutingUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RoutingUpdate.newBuilder() to construct.
  private RoutingUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RoutingUpdate() {
    mRNs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    subjects_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new RoutingUpdate();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MMTPMessages.internal_static_RoutingUpdate_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MMTPMessages.internal_static_RoutingUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RoutingUpdate.class, Builder.class);
  }

  public static final int MRNS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList mRNs_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string MRNs = 1;</code>
   * @return A list containing the mRNs.
   */
  public com.google.protobuf.ProtocolStringList
      getMRNsList() {
    return mRNs_;
  }
  /**
   * <code>repeated string MRNs = 1;</code>
   * @return The count of mRNs.
   */
  public int getMRNsCount() {
    return mRNs_.size();
  }
  /**
   * <code>repeated string MRNs = 1;</code>
   * @param index The index of the element to return.
   * @return The mRNs at the given index.
   */
  public String getMRNs(int index) {
    return mRNs_.get(index);
  }
  /**
   * <code>repeated string MRNs = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the mRNs at the given index.
   */
  public com.google.protobuf.ByteString
      getMRNsBytes(int index) {
    return mRNs_.getByteString(index);
  }

  public static final int SUBJECTS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList subjects_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string subjects = 2;</code>
   * @return A list containing the subjects.
   */
  public com.google.protobuf.ProtocolStringList
      getSubjectsList() {
    return subjects_;
  }
  /**
   * <code>repeated string subjects = 2;</code>
   * @return The count of subjects.
   */
  public int getSubjectsCount() {
    return subjects_.size();
  }
  /**
   * <code>repeated string subjects = 2;</code>
   * @param index The index of the element to return.
   * @return The subjects at the given index.
   */
  public String getSubjects(int index) {
    return subjects_.get(index);
  }
  /**
   * <code>repeated string subjects = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the subjects at the given index.
   */
  public com.google.protobuf.ByteString
      getSubjectsBytes(int index) {
    return subjects_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < mRNs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mRNs_.getRaw(i));
    }
    for (int i = 0; i < subjects_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subjects_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < mRNs_.size(); i++) {
        dataSize += computeStringSizeNoTag(mRNs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMRNsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < subjects_.size(); i++) {
        dataSize += computeStringSizeNoTag(subjects_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSubjectsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RoutingUpdate)) {
      return super.equals(obj);
    }
    RoutingUpdate other = (RoutingUpdate) obj;

    if (!getMRNsList()
        .equals(other.getMRNsList())) return false;
    if (!getSubjectsList()
        .equals(other.getSubjectsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMRNsCount() > 0) {
      hash = (37 * hash) + MRNS_FIELD_NUMBER;
      hash = (53 * hash) + getMRNsList().hashCode();
    }
    if (getSubjectsCount() > 0) {
      hash = (37 * hash) + SUBJECTS_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RoutingUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoutingUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoutingUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoutingUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoutingUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoutingUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoutingUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RoutingUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RoutingUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RoutingUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RoutingUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RoutingUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RoutingUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RoutingUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RoutingUpdate)
          RoutingUpdateOrBuilder
  {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MMTPMessages.internal_static_RoutingUpdate_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MMTPMessages.internal_static_RoutingUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoutingUpdate.class, Builder.class);
    }

    // Construct using MMS.MMTP.RoutingUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mRNs_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      subjects_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MMTPMessages.internal_static_RoutingUpdate_descriptor;
    }

    @Override
    public RoutingUpdate getDefaultInstanceForType() {
      return RoutingUpdate.getDefaultInstance();
    }

    @Override
    public RoutingUpdate build() {
      RoutingUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RoutingUpdate buildPartial() {
      RoutingUpdate result = new RoutingUpdate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(RoutingUpdate result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        mRNs_.makeImmutable();
        result.mRNs_ = mRNs_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        subjects_.makeImmutable();
        result.subjects_ = subjects_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RoutingUpdate) {
        return mergeFrom((RoutingUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RoutingUpdate other) {
      if (other == RoutingUpdate.getDefaultInstance()) return this;
      if (!other.mRNs_.isEmpty()) {
        if (mRNs_.isEmpty()) {
          mRNs_ = other.mRNs_;
          bitField0_ |= 0x00000001;
        } else {
          ensureMRNsIsMutable();
          mRNs_.addAll(other.mRNs_);
        }
        onChanged();
      }
      if (!other.subjects_.isEmpty()) {
        if (subjects_.isEmpty()) {
          subjects_ = other.subjects_;
          bitField0_ |= 0x00000002;
        } else {
          ensureSubjectsIsMutable();
          subjects_.addAll(other.subjects_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              ensureMRNsIsMutable();
              mRNs_.add(s);
              break;
            } // case 10
            case 18: {
              String s = input.readStringRequireUtf8();
              ensureSubjectsIsMutable();
              subjects_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList mRNs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMRNsIsMutable() {
      if (!mRNs_.isModifiable()) {
        mRNs_ = new com.google.protobuf.LazyStringArrayList(mRNs_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @return A list containing the mRNs.
     */
    public com.google.protobuf.ProtocolStringList
        getMRNsList() {
      mRNs_.makeImmutable();
      return mRNs_;
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @return The count of mRNs.
     */
    public int getMRNsCount() {
      return mRNs_.size();
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @param index The index of the element to return.
     * @return The mRNs at the given index.
     */
    public String getMRNs(int index) {
      return mRNs_.get(index);
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the mRNs at the given index.
     */
    public com.google.protobuf.ByteString
        getMRNsBytes(int index) {
      return mRNs_.getByteString(index);
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @param index The index to set the value at.
     * @param value The mRNs to set.
     * @return This builder for chaining.
     */
    public Builder setMRNs(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMRNsIsMutable();
      mRNs_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @param value The mRNs to add.
     * @return This builder for chaining.
     */
    public Builder addMRNs(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMRNsIsMutable();
      mRNs_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @param values The mRNs to add.
     * @return This builder for chaining.
     */
    public Builder addAllMRNs(
        Iterable<String> values) {
      ensureMRNsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, mRNs_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMRNs() {
      mRNs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string MRNs = 1;</code>
     * @param value The bytes of the mRNs to add.
     * @return This builder for chaining.
     */
    public Builder addMRNsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMRNsIsMutable();
      mRNs_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList subjects_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSubjectsIsMutable() {
      if (!subjects_.isModifiable()) {
        subjects_ = new com.google.protobuf.LazyStringArrayList(subjects_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @return A list containing the subjects.
     */
    public com.google.protobuf.ProtocolStringList
        getSubjectsList() {
      subjects_.makeImmutable();
      return subjects_;
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @return The count of subjects.
     */
    public int getSubjectsCount() {
      return subjects_.size();
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @param index The index of the element to return.
     * @return The subjects at the given index.
     */
    public String getSubjects(int index) {
      return subjects_.get(index);
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the subjects at the given index.
     */
    public com.google.protobuf.ByteString
        getSubjectsBytes(int index) {
      return subjects_.getByteString(index);
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @param index The index to set the value at.
     * @param value The subjects to set.
     * @return This builder for chaining.
     */
    public Builder setSubjects(
        int index, String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSubjectsIsMutable();
      subjects_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @param value The subjects to add.
     * @return This builder for chaining.
     */
    public Builder addSubjects(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSubjectsIsMutable();
      subjects_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @param values The subjects to add.
     * @return This builder for chaining.
     */
    public Builder addAllSubjects(
        Iterable<String> values) {
      ensureSubjectsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, subjects_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubjects() {
      subjects_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string subjects = 2;</code>
     * @param value The bytes of the subjects to add.
     * @return This builder for chaining.
     */
    public Builder addSubjectsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSubjectsIsMutable();
      subjects_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RoutingUpdate)
  }

  // @@protoc_insertion_point(class_scope:RoutingUpdate)
  private static final RoutingUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RoutingUpdate();
  }

  public static RoutingUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoutingUpdate>
      PARSER = new com.google.protobuf.AbstractParser<RoutingUpdate>() {
    @Override
    public RoutingUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RoutingUpdate> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RoutingUpdate> getParserForType() {
    return PARSER;
  }

  @Override
  public RoutingUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

