// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MMTPMessages.proto

package Protocols.MMTP.MessageFormats;

public interface SubjectCastApplicationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubjectCastApplicationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string subject = 2;</code>
   * @return The subject.
   */
  String getSubject();
  /**
   * <code>string subject = 2;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string sender = 3;</code>
   * @return The sender.
   */
  String getSender();
  /**
   * <code>string sender = 3;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return Whether the expires field is set.
   */
  boolean hasExpires();
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return The expires.
   */
  com.google.protobuf.Timestamp getExpires();
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresOrBuilder();

  /**
   * <code>bytes payload = 5;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
